# -*- coding: utf-8 -*-
"""Diabetes_app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17N4Qh7gL4glcXGW0QelSafQ8rU_ljWmR
"""

! pip install streamlit joblib

import streamlit as st
import joblib

model = joblib.load('diabetes_model.pkl')

st.title("🩺 Diabetes Prediction App")
st.write("Enter patient details to check diabetes prediction.")

age = st.number_input("Enter Age", min_value=1, max_value=120, value=30)
mass = st.number_input("Enter Body Mass Index (mass)", min_value=10.0, max_value=100.0, value=30.0)
insu = st.number_input("Enter Insulin Level", min_value=0, max_value=900, value=80)
plas = st.number_input("Enter Plasma Glucose Level", min_value=0, max_value=200, value=100)
pres = st.number_input("Enter Blood Pressure", min_value=0, max_value=140, value=70)

if st.button("Predict"):
    result = model.predict([[age, mass, insu, plas, pres]])
    if result[0] == "tested_positive":
        st.error("🔴 The model predicts **Diabetes**")
    else:
        st.success("🟢 The model predicts **No Diabetes**")